name: VoidMute
main: RealMute\Main
version: 4.0.1
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
load: POSTWORLD
author: VMPE Development Team
description: A chat management plugin with many extra features.
website: Not showing.

commands:
 voidmute:
  aliases: 
    - vmt
  description: "VoidMute options"
  usage: "/voidmute help|<options>"
  permission: voidmute.option
 vmute:
  description: "Mute a player"
  usage: "/vmute <player> [time in minutes]"
  permission: voidmute.mute
 vunmute:
  description: "Unmute a player"
  usage: "/vunmute <player>"
  permission: voidmute.unmute
 muteall:
  description: "Mute all players"
  usage: "/muteall"
  permission: voidmute.muteall
 unmuteall:
  description: "Unmute all players"
  usage: "/unmuteall"
  permission: voidmute.unmuteall
  
permissions:
 voidmute:
  description: "Allows all VoidMute commands"
  default: op
  children:
   voidmute.muteignored:
    description: "Allows sending messages when all players are muted"
    default: op
   voidmute.option:
    description: "Allows changing VoidMute options"
    default: op
   voidmute.mute:
    description: "Allows muting individual players"
    default: op
   voidmute.unmute:
    description: "Allows unmuting individual players"
    default: op
   voidmute.muteall:
    description: "Allows muting all players"
    default: op
   voidmute.unmuteall:
    description: "Allows unmuting individual players"
    default: op
